const BACKGROUND_COLOR = "#E6F7FF"
const PRIMARY_COLOR = "#333333"
const SECONDARY_COLOR = "#CCCCCC"
const HEADING1_COLOR = "#4B0082"
const HEADING2_COLOR = "#008080"

export {
    BACKGROUND_COLOR,
    PRIMARY_COLOR,
    SECONDARY_COLOR,
    HEADING1_COLOR,
    HEADING2_COLOR
}